### ISSUE TITLE
Drop Python 3.6?

### ISSUE THREAD

**Issue by boeddeker** [fgnt/padertorch#139]
Python 3.6 had eol last year (23 Dec 2021).
Should we drop test for it?

Why:
The tests in #138 fail, because python 3.6 has a different representer for annotations.
Finding a workaround for the doctest is annoying and since Python 3.6 is eol,
I thought we could drop it.

**Comment by thequilo** [comment]
I think that we can safely drop Python 3.6 since it is officially not supported anymore

**Comment by boeddeker** [comment]
Since no one complained, I will remove them.
